name: Render YAML Resume to HTML and PDF
description: Takes a YAML document and renders it as HTML, then uses whtmltopdf to generate a PDF.
on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branch to run the workflow on
        required: true
        default: main
      resume_path:
        description: Path to the resume file
        required: true
        default: resume_details.yaml
env:
    BRANCH: ${{ github.event.inputs.branch || github.ref }}
    RESUME_PATH: ${{ github.event.inputs.resume_path }}
jobs:
  render-resume:
    env:
      RESUME_FILENAME: alastair-${{ inputs.branch }}-resume.html
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        ref: ${{ env.BRANCH }}
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        ls -lah
        pip install -r requirements.txt

    - name: Render HTML resume
      run: |
        ./resume_generator.py \
          --yaml-file-name ${{ env.RESUME_PATH }} \
          --output-file-name ${{ env.RESUME_FILENAME }}

    - name: Install wkhtmltopdf
      run: |
        sudo apt-get update
        sudo apt-get install -y wkhtmltopdf

    - name: Convert HTML to PDF
      run: |
        PDF_FILENAME=$(echo '${{ env.RESUME_FILENAME }}' | sed 's/\.html$//g')
        echo "PDF_FILENAME=${PDF_FILENAME}.pdf" | tee -a $GITHUB_ENV
        wkhtmltopdf "${{ env.RESUME_FILENAME }}" "${PDF_FILENAME}.pdf"

    - name: Archive rewritten resume
      uses: actions/upload-artifact@v7
      with:
        name: resume-artifacts
        path: |
          ${{ env.PDF_FILENAME }}
          ${{ env.RESUME_FILENAME }}
