name: Check Candidate Qualification (Gemini)
description: Use Google Gemini to evaluate if a candidate is qualified for a job based on their resume and the job description.

inputs:
  GOOGLE_API_KEY:
    description: Google API Key For Gemini
    required: true
  GEMINI_MODEL:
    description: Gemini Model
    required: true
    default: gemini-2.0-flash
  RESUME_TEXT:
    description: Resume Text
    required: true
  RESUME_MIME_TYPE:
    description: Resume Mime Type
    required: true
    default: text/plain
  JOB_DESCRIPTION:
    description: Job Description
    required: true
  JOB_DESCRIPTION_MIME_TYPE:
    description: Job Description Mime Type
    required: true
    default: text/plain

runs:
  using: composite
  steps:
    - name: Build Payload
      uses: actions/github-script@v6
      with:
        script: |
          const fs = require('fs');
          const payload = {
            contents: [{
              parts: [
                {
                  text: `Compare the resume and job description and provide a JSON formatted response containing the following key/value pairs:
                  - score: a score between 1 and 100 for how well the resume matches the job description.
                  - explanation: an explanation of the score no longer than 250 words.
                  - deficiencies: a list of deficiencies in the resume that the candidate likely possesses, but could be better highlighted in the resume.
                  - strengths: a list of strengths in the resume that the candidate possesses.
                  - recommendations: a list of specific changes that the candidate should make to their resume to improve their chances of getting the job.

                  The response should be raw JSON, without any additional text or formatting. The JSON should use 2 spaces for indentation.`
                },
                {
                  inline_data: {
                    mime_type: process.env.INPUT_RESUME_MIME_TYPE,
                    data: process.env.INPUT_RESUME_TEXT
                  }
                },
                {
                  inline_data: {
                    mime_type: process.env.INPUT_JOB_DESCRIPTION_MIME_TYPE,
                    data: process.env.INPUT_JOB_DESCRIPTION
                  }
                }
              ]
            }]
          };
          const payload_string = JSON.stringify(payload, null, 2);
          const response = await github.request(`POST https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key=${process.env.INPUT_GOOGLE_API_KEY}`, {
            headers: {
              'content-type': 'application/json'
            },
            data: payload_string
          });

          console.log(response.data);
