name: Score Resume

on:
  push:

jobs:
  score_resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: dev-dull/resume
          token: ${{ secrets.REPO_TOKEN }}

      - name: Supress personal information (no-op)
        shell: bash
        run: |
          # ${{secrets.ADDRESS}}
          # ${{secrets.EMAIL}}
          # ${{secrets.PHONE}}

      - name: Set Resume Text
        uses: actions/github-script@v6
        id: set-output
        with:
          script: |
            const fs = require('fs')
            const resumeText = fs.readFileSync('resume_details.yaml', 'utf8')
            core.exportVariable('RESUME_TEXT', resumeText)

      - name: Run gemini-qualified action
        id: gemini-score
        uses: dev-dull/job-search-automations/gemini-qualified@gemini-qualify
        with:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GEMINI_MODEL: gemini-2.0-flash
          RESUME_TEXT: ${{ env.RESUME_TEXT }}
          JOB_DESCRIPTION: ${{ secrets.TESTING_DELETE }}

      - name: Debug Outputs
        run: |
          echo "RESPONSE_TEXT: ${{ steps.gemini-score.outputs.RESPONSE_TEXT }}"
          echo "RAW: ${{ steps.gemini-score.outputs.RAW }}"

      - name: Print Gemini Score
        run: |
          echo "## Gemini Score:" >> $GITHUB_STEP_SUMMARY
          echo -e 'Gemini text:\n```json\n${{ steps.gemini-score.outputs.RESPONSE_TEXT }}\n```' >> $GITHUB_STEP_SUMMARY
          echo "## Gemini Raw:" >> $GITHUB_STEP_SUMMARY
          echo -e 'Gemini Raw Response:\n```json\n${{ steps.gemini-score.outputs.RAW }}\n```' >> $GITHUB_STEP_SUMMARY
