name: Score Resume

on:
  push:

jobs:
  score_resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: dev-dull/resume
          token: ${{ secrets.REPO_TOKEN }}

      - name: Supress personal information (no-op)
        shell: bash
        run: |
          # ${{secrets.ADDRESS}}
          # ${{secrets.EMAIL}}
          # ${{secrets.PHONE}}

      - name: Set Resume Text
        uses: actions/github-script@v7
        id: set-output
        with:
          script: |
            const fs = require('fs')
            const resumeText = fs.readFileSync('resume_details.yaml', 'utf8')
            core.exportVariable('RESUME_TEXT', resumeText)

      - name: Run gemini-qualified action
        id: gemini-check
        uses: dev-dull/job-search-automations/gemini-qualified@gemini-qualify
        with:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
          GEMINI_MODEL: gemini-2.0-flash
          RESUME_TEXT: ${{ env.RESUME_TEXT }}
          JOB_DESCRIPTION: ${{ secrets.TESTING_DELETE }}
          CAREER_GROWTH_KEYWORDS: Senior DevOps Kubernetes Docker Terraform Vault Ansible Linux

      - name: Print Gemini Score
        uses: actions/github-script@v7
        env:
          RAW: ${{ steps.gemini-check.outputs.RAW }}
          RESPONSE_TEXT: ${{ steps.gemini-check.outputs.RESPONSE_TEXT }}
        with:
          script: |
            try {
              const response = JSON.parse(process.env.RESPONSE_TEXT);

              core.summary
                .addHeading('About The Candidate')
                .addHeading(`Candidate Score: \`${response.candidate_score}\``, 2)
                .addHeading(`Career Growth Score: \`${response.career_growth_score}\``, 2)
                .addHeading('Candidate Explanation', 2)
                .addRaw(response.candidate_explanation)
                .addHeading('Candidate Deficiencies', 2)
                .addList(response.candidate_deficiencies)
                .addHeading('Candidate Strengths', 2)
                .addList(response.candidate_strengths)
                .addHeading('Candidate Recommendations', 2)
                .addList(response.candidate_recommendations)
                .addHeading('About The Job')
                .addHeading(`Job Description Score: \`${response.job_description_score}\``, 2)
                .addHeading('Job Description Explanation', 2)
                .addRaw(response.job_description_explanation)
                .addHeading('Job Description Deficiencies', 2)
                .addList(response.job_description_deficiencies)
                .addHeading(`About ${response.job_company_name}`)
                .addHeading('Job Company Description', 2)
                .addRaw(response.job_company_description)
                .addHeading(`Job Company Sentiment Score: \`${response.job_company_sentiment}\``, 2)
                .addHeading('Job Company Explanation', 2)
                .addRaw(response.job_company_explanation)
                .write()
            } catch (error) {
              core.setFailed(`Error parsing JSON response: ${error.message}`);
              core.summary
                .addCodeBlock(process.env.RESPONSE_TEXT)
                .addError(error.message)
                .write()
            }
